### ISSUE TITLE
how to remove a already added Script?

### ISSUE THREAD

**Issue by slekk** [xmpie-users/uStore-js#2]
Hi,

Please can you tell me, how I can remove a already added Java Script.
I had added the autoRecalculatePrices Script and I want to know, how I can remove it.

thanks,
regards,
slekk

**Comment by dotanxmpie** [comment]
Hello Slekk,

The way to remove the JS that you added is the same way as adding it.

See [the instructions for adding JS in here](https://gist.github.com/scouch1/f9787fbc4ab818600d2327bbe7dbec1f).

Simply go into the settings, and remove the JS that you added.

I would recommend that before you delete it, you create a TXT file in a safe place, and paste into it the exact code that you have in your store, for safekeeping.

Regards,
Dotan
