### ISSUE TITLE
Using a recipient data source for multiple delivery addresses

### ISSUE THREAD

**Issue by stevehopkinstfg** [xmpie-users/uStore-js#3]
Can use a recipient data table for delivery addresses? We are currently using a recipient data table for the product itself, but it would save our customers a lot of time if they could also use a recipient data table for the delivery. Any help would be much appreciated.

Thank you :)

**Comment by c0d3gr1** [comment]
Hi Steve H - I'm not completely sure what you are asking.  In uStore, the store users could be given a list of mailing addresses, which they'd have to choose from.  The advantage to this is that the list is set for company locations, this way no one types the wrong info. The disadvantage, is that they can only choose from this list. ... Does this sound like what you wanted?
deb

**Comment by stevehopkinstfg** [comment]
Hi Deb - Apologies I don't think I was very clear. 
Basically we have a customer who orders large quantities of certificates at one time and these certificates go to quite a number of locations. Currently they use a data table to personalise the certificates, but they have to manually match each certificate to each address at the checkout stage. I was hoping to skip this step by using a data table with mailing addresses included. 
Based on your reply I am guessing you can't do this?

**Comment by c0d3gr1** [comment]
Hi, I think we had another customer with a similar need, they reached out to Igor/Pro Services to get something built that would work.  (Have you been to the xmpie google forum?? They might have discussed this there.) 
Another way, which is still manual but maybe helps some, you can create a product property that allows the customer to upload a spreadsheet with data, in this case it could be your list.  If you have one order, the uploaded sheet could help with distribution. The problem with this of course is shipping and if you charge tax based on the shipping location on this product as the shipping would look like one location.

**Comment by stevehopkinstfg** [comment]
Oh ok I understand. I haven't been to the google forum, but I will check it out. 
I think the product property idea is a good idea for the short term! :)
Thank you for your help!

**Comment by NeilKMC** [comment]
You could add an extra page in your Indesign document, so p1 is the certificate and p2 is a delivery note. Use a workflow to send them to different printers if needed.
