### ISSUE TITLE
Change clearing method based on user group

### ISSUE THREAD

**Issue by GaryWagner** [xmpie-users/uStore-js#5]
Not sure which version of uStore broke this but it used to work for our stores but recently has stopped showing any clearing methods.

The issue seems to be that "xmp.sdk.storeFrontParams.currentUser.userGroups" return an array of clearing IDs and Names.

Changing this line:

if($.inArray(parseInt(groupId), UserGroupsByUserArray) >= 0){

to

if($.inArray(parseInt(groupId), UserGroupsByUserArray.map(u => x.ID)) >= 0){

Solves the issue.

Gary

**Comment by scouch1** [comment]
Hi Gary,

Thanks for letting us know there was a change - and double thank you for the solution!
I have updated and tested the change in the wiki page at: https://github.com/xmpie-users/uStore-js/wiki/Change-clearing-method-based-on-user-group

Steve
